# Site settings
title: JL Blog                     #你博客的标题
SEOTitle: JL Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: You@gmail.com    
description: "JL Blog"              #网站介绍
keyword: "JL, JL Blog, 柏荧的博客, ML" #关键词
url: "https://gjl.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Disqus settings（https://disqus.com/）
disqus_username: gjl


# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
